STATION:
  latitude: 42.5
  longitude: -71.5
  name: Haystack
EMERGENCY_CONTACT:
  name: John Doe
  email: test@example.com
  phone_number: 555-555-5555
AZLIMITS:
  lower_bound: 38.0
  upper_bound: 355.0
ELLIMITS:
  lower_bound: 0.0
  upper_bound: 89.0
STOW_LOCATION:
  azimuth: 38.0
  elevation: 0.0
CAL_LOCATION:
  azimuth: 120.0
  elevation: 7.0
MOTOR_TYPE: NONE
MOTOR_PORT: /dev/ttyUSB0
RADIO_CF: 1420000000
RADIO_SF: 2000000
RADIO_NUM_BINS: 4096
RADIO_INTEG_CYCLES: 1000
RADIO_AUTOSTART: Yes
BEAMWIDTH: 7.0
TSYS: 171
TCAL: 290
SAVE_DIRECTORY: ~/Desktop/SRT-Saves
