STATION:
  latitude: 42.5
  longitude: -71.5
  name: Haystack
AZLIMITS:
  lower_bound: 10.0
  upper_bound: 359.0
ELLIMITS:
  lower_bound: -1.0
  upper_bound: 90.0
STOW_LOCATION:
  azimuth: 10.0
  elevation: -1.0
MOTOR_OFFSETS:
  azimuth: 0.0
  elevation: 0.0
MOTOR_TYPE: ALFASPID
MOTOR_PORT: /dev/ttyUSB0
RADIO_CF: 100000000
RADIO_SF: 2000000
BEAMWIDTH: 7.0
TSYS: 171
TCAL: 290
