STATION: include('location')
AZLIMITS: include('limit')
ELLIMITS: include('limit')
STOW_LOCATION: include('az_el_point')
MOTOR_OFFSETS: include('az_el_point')
MOTOR_TYPE: enum('ALFASPID', 'H180MOUNT')
MOTOR_PORT: str()
RADIO_CF: num()
RADIO_SF: num()
BEAMWIDTH: num()
TSYS: num()
TCAL: num()
---
location:
    latitude: num()
    longitude: num()
    name: str()
---
limit:
    lower_bound: num()
    upper_bound: num()
---
az_el_point:
    azimuth: num()
    elevation: num()