STATION: include('location')
EMERGENCY_CONTACT: include('contact_info')
AZLIMITS: include('limit')
ELLIMITS: include('limit')
STOW_LOCATION: include('az_el_point')
CAL_LOCATION: include('az_el_point')
MOTOR_TYPE: enum('ALFASPID', 'H180MOUNT', 'PUSHROD', 'NONE')
MOTOR_PORT: str()
RADIO_CF: num()
RADIO_SF: num()
RADIO_NUM_BINS: num()
RADIO_INTEG_CYCLES: num()
RADIO_AUTOSTART: bool()
BEAMWIDTH: num()
TSYS: num()
TCAL: num()
SAVE_DIRECTORY: str()
---
location:
    latitude: num()
    longitude: num()
    name: str()
---
limit:
    lower_bound: num()
    upper_bound: num()
---
az_el_point:
    azimuth: num()
    elevation: num()
---
contact_info:
    name: str()
    email: str()
    phone_number: str()